<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="text" omit-xml-declaration="yes" encoding="UTF-8" indent="no"/>
    
        <xsl:template match="iet">
            <xsl:text>#####   WARNING!!! - This configuration file generated by Openfiler. DO NOT MANUALLY EDIT.  #####  </xsl:text>
            <xsl:text>&#10; &#10; &#10;</xsl:text>
            <xsl:call-template name="isns"/>
            <xsl:call-template name="globalUsers"/>
            <xsl:text>&#10; &#10;</xsl:text>
            <xsl:call-template name="Targets"/>
        </xsl:template>
        
        <xsl:template name="globalUsers">
            <xsl:for-each select="globalsettings">
                <xsl:call-template name="Users"/>
            </xsl:for-each>
        </xsl:template>
        
        <xsl:template name="isns">
            <xsl:for-each select="globalsettings/isns">
                <xsl:choose>
                    <xsl:when test="@server">
                        <xsl:text>&#x9;iSNSServer &#x9;</xsl:text><xsl:value-of select="@server"/><xsl:text>&#10;</xsl:text>
                    </xsl:when>
                </xsl:choose>
            </xsl:for-each>
        </xsl:template>
        
        <xsl:template name="Targets">
            <xsl:for-each select="targets/target">
                <xsl:text>Target </xsl:text> <xsl:value-of select="@Name"/><xsl:text>&#10;</xsl:text>
                <xsl:call-template name="targetSettings"/>
                <xsl:call-template name="Users"/>
                <xsl:call-template name="targetLuns"/>
                <xsl:text>&#10;&#10;</xsl:text>
            </xsl:for-each>
        </xsl:template>
        
                
        <xsl:template name="targetSettings">
            <xsl:for-each select="HeaderDigest">
                <xsl:text>&#x9;HeaderDigest </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="DataDigest">
                <xsl:text>&#x9;DataDigest </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="MaxConnections">
                <xsl:text>&#x9;MaxConnections </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>    
            <xsl:for-each select="InitialR2T">
                <xsl:text>&#x9;InitialR2T </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="ImmediateData">
                <xsl:text>&#x9;ImmediateData </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="MaxRecvDataSegmentLength">
                <xsl:text>&#x9;MaxRecvDataSegmentLength </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="MaxXmitDataSegmentLength">
                <xsl:text>&#x9;MaxXmitDataSegmentLength </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>    
            <xsl:for-each select="MaxBurstLength">
                <xsl:text>&#x9;MaxBurstLength </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>    
            <xsl:for-each select="FirstBurstLength">
                <xsl:text>&#x9;FirstBurstLength </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="DefaultTime2Wait">
                <xsl:text>&#x9;DefaultTime2Wait </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="DefaultTime2Retain">
                <xsl:text>&#x9;DefaultTime2Retain </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="MaxOutstandingR2T">
                <xsl:text>&#x9;MaxOutstandingR2T </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="DataPDUInOrder">
                <xsl:text>&#x9;DataPDUInOrder </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="DataSequenceInOrder">
                <xsl:text>&#x9;DataSequenceInOrder </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
            <xsl:for-each select="ErrorRecoveryLevel">
                <xsl:text>&#x9;ErrorRecoveryLevel </xsl:text><xsl:value-of select="@value"/><xsl:text>&#10;</xsl:text>
            </xsl:for-each>
        </xsl:template>
        
        <xsl:template name="targetLuns">
            <xsl:for-each select="lun">
                <xsl:text>&#x9;</xsl:text> <!-- tab character -->
                <xsl:text>Lun </xsl:text> <xsl:value-of select="@Id"/><xsl:text> </xsl:text>
                <xsl:text>Path=</xsl:text><xsl:value-of select="@Path"/><xsl:text>,</xsl:text>
                <xsl:text>Type=</xsl:text><xsl:value-of select="@Type"/><xsl:text>,</xsl:text>
                <xsl:text>ScsiSN=</xsl:text><xsl:value-of select="@ScsiSN"/><xsl:text>,</xsl:text>
                <xsl:text>ScsiId=</xsl:text><xsl:value-of select="@ScsiId"/><xsl:text>,</xsl:text>
                <xsl:text>IOMode=</xsl:text><xsl:value-of select="@IOMode"/>
                <xsl:text>&#10;</xsl:text> <!-- newline character -->
            </xsl:for-each>
        </xsl:template>
        
        <xsl:template name="Users">
                <xsl:for-each select="IncomingUser">
                        <xsl:text>&#9;</xsl:text>
                        <xsl:text>IncomingUser </xsl:text><xsl:value-of select="@username"/><xsl:text> </xsl:text><xsl:value-of select="@password"/>
                        <xsl:text>&#10;</xsl:text>
                </xsl:for-each>
                <xsl:for-each select="OutgoingUser">
                        <xsl:text>&#9;</xsl:text>
                        <xsl:text>OutgoingUser </xsl:text><xsl:value-of select="@username"/><xsl:text> </xsl:text><xsl:value-of select="@password"/>
                        <xsl:text>&#10;</xsl:text>
                </xsl:for-each>
        </xsl:template>
</xsl:stylesheet>
