<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    
    <xsl:output method="text" omit-xml-declaration="yes" encoding="UTF-8" indent="no"/>
    
    <xsl:template match="aclentries">
        <xsl:text>#####   WARNING!!! - This configuration file generated by Openfiler. DO NOT MANUALLY EDIT.  #####
            
            
        </xsl:text>
        <xsl:text>
ACL all 0.0.0.0/0
        </xsl:text>
        <xsl:apply-templates select="hostentry" />
        <xsl:call-template name="allacls"/>
    </xsl:template>
    
    
    
<xsl:template match="hostentry">
   
<xsl:text>
ACL </xsl:text><xsl:value-of select="@id"/><xsl:text> </xsl:text><xsl:value-of select="@iphostname"/><xsl:text>/</xsl:text><xsl:value-of select="@netmask"/>
<xsl:text>             
</xsl:text>
</xsl:template>
    
<xsl:template name="allacls">
<xsl:for-each select="//hostentry">
<xsl:choose>
<xsl:when test="contains(@mode, 'accept')">
<xsl:text>
ACCEPT </xsl:text><xsl:value-of select="@id"/>
<xsl:text>
</xsl:text>
</xsl:when>
<xsl:otherwise>
<xsl:text>
REJECT </xsl:text><xsl:value-of select="@id"/>
<xsl:text>
</xsl:text>
</xsl:otherwise>
</xsl:choose>
            
</xsl:for-each>
<xsl:text>
REJECT all</xsl:text>
</xsl:template>
    
</xsl:stylesheet>
